// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrCall}
 */
public final class IrCall extends
    org.jetbrains.kotlin.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrCall)
    IrCallOrBuilder {
  // Use IrCall.newBuilder() to construct.
  private IrCall(org.jetbrains.kotlin.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private IrCall(boolean noInit) { this.unknownFields = org.jetbrains.kotlin.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final IrCall defaultInstance;
  public static IrCall getDefaultInstance() {
    return defaultInstance;
  }

  public IrCall getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final org.jetbrains.kotlin.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final org.jetbrains.kotlin.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private IrCall(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    org.jetbrains.kotlin.protobuf.UnknownFieldSet.Builder unknownFields =
        org.jetbrains.kotlin.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            symbol_ = input.readInt64();
            break;
          }
          case 18: {
            MemberAccessCommon.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = memberAccess_.toBuilder();
            }
            memberAccess_ = input.readMessage(MemberAccessCommon.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(memberAccess_);
              memberAccess_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            super_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            originName_ = input.readInt32();
            break;
          }
        }
      }
    } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrCall_descriptor;
  }

  protected org.jetbrains.kotlin.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrCall_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            IrCall.class, Builder.class);
  }

  public static org.jetbrains.kotlin.protobuf.Parser<IrCall> PARSER =
      new org.jetbrains.kotlin.protobuf.AbstractParser<IrCall>() {
    public IrCall parsePartialFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
      return new IrCall(input, extensionRegistry);
    }
  };

  @Override
  public org.jetbrains.kotlin.protobuf.Parser<IrCall> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int SYMBOL_FIELD_NUMBER = 1;
  private long symbol_;
  /**
   * <code>required int64 symbol = 1;</code>
   */
  public boolean hasSymbol() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 symbol = 1;</code>
   */
  public long getSymbol() {
    return symbol_;
  }

  public static final int MEMBER_ACCESS_FIELD_NUMBER = 2;
  private MemberAccessCommon memberAccess_;
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
   */
  public boolean hasMemberAccess() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
   */
  public MemberAccessCommon getMemberAccess() {
    return memberAccess_;
  }
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
   */
  public MemberAccessCommonOrBuilder getMemberAccessOrBuilder() {
    return memberAccess_;
  }

  public static final int SUPER_FIELD_NUMBER = 3;
  private long super_;
  /**
   * <code>optional int64 super = 3;</code>
   */
  public boolean hasSuper() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int64 super = 3;</code>
   */
  public long getSuper() {
    return super_;
  }

  public static final int ORIGIN_NAME_FIELD_NUMBER = 4;
  private int originName_;
  /**
   * <code>optional int32 origin_name = 4;</code>
   */
  public boolean hasOriginName() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 origin_name = 4;</code>
   */
  public int getOriginName() {
    return originName_;
  }

  private void initFields() {
    symbol_ = 0L;
    memberAccess_ = MemberAccessCommon.getDefaultInstance();
    super_ = 0L;
    originName_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSymbol()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMemberAccess()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getMemberAccess().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.jetbrains.kotlin.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, symbol_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, memberAccess_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, super_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, originName_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt64Size(1, symbol_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeMessageSize(2, memberAccess_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt64Size(3, super_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt32Size(4, originName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static IrCall parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IrCall parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IrCall parseFrom(byte[] data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static IrCall parseFrom(
      byte[] data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static IrCall parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static IrCall parseFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static IrCall parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static IrCall parseDelimitedFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static IrCall parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static IrCall parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(IrCall prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      org.jetbrains.kotlin.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrCall}
   */
  public static final class Builder extends
      org.jetbrains.kotlin.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrCall)
      IrCallOrBuilder {
    public static final org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrCall_descriptor;
    }

    protected org.jetbrains.kotlin.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IrCall.class, Builder.class);
    }

    // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrCall.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.jetbrains.kotlin.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.jetbrains.kotlin.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getMemberAccessFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      symbol_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (memberAccessBuilder_ == null) {
        memberAccess_ = MemberAccessCommon.getDefaultInstance();
      } else {
        memberAccessBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      super_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      originName_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrCall_descriptor;
    }

    public IrCall getDefaultInstanceForType() {
      return IrCall.getDefaultInstance();
    }

    public IrCall build() {
      IrCall result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public IrCall buildPartial() {
      IrCall result = new IrCall(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.symbol_ = symbol_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (memberAccessBuilder_ == null) {
        result.memberAccess_ = memberAccess_;
      } else {
        result.memberAccess_ = memberAccessBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.super_ = super_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.originName_ = originName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(org.jetbrains.kotlin.protobuf.Message other) {
      if (other instanceof IrCall) {
        return mergeFrom((IrCall)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(IrCall other) {
      if (other == IrCall.getDefaultInstance()) return this;
      if (other.hasSymbol()) {
        setSymbol(other.getSymbol());
      }
      if (other.hasMemberAccess()) {
        mergeMemberAccess(other.getMemberAccess());
      }
      if (other.hasSuper()) {
        setSuper(other.getSuper());
      }
      if (other.hasOriginName()) {
        setOriginName(other.getOriginName());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSymbol()) {
        
        return false;
      }
      if (!hasMemberAccess()) {
        
        return false;
      }
      if (!getMemberAccess().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      IrCall parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (IrCall) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long symbol_ ;
    /**
     * <code>required int64 symbol = 1;</code>
     */
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 symbol = 1;</code>
     */
    public long getSymbol() {
      return symbol_;
    }
    /**
     * <code>required int64 symbol = 1;</code>
     */
    public Builder setSymbol(long value) {
      bitField0_ |= 0x00000001;
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 symbol = 1;</code>
     */
    public Builder clearSymbol() {
      bitField0_ = (bitField0_ & ~0x00000001);
      symbol_ = 0L;
      onChanged();
      return this;
    }

    private MemberAccessCommon memberAccess_ = MemberAccessCommon.getDefaultInstance();
    private org.jetbrains.kotlin.protobuf.SingleFieldBuilder<
        MemberAccessCommon, MemberAccessCommon.Builder, MemberAccessCommonOrBuilder> memberAccessBuilder_;
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public boolean hasMemberAccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public MemberAccessCommon getMemberAccess() {
      if (memberAccessBuilder_ == null) {
        return memberAccess_;
      } else {
        return memberAccessBuilder_.getMessage();
      }
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public Builder setMemberAccess(MemberAccessCommon value) {
      if (memberAccessBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        memberAccess_ = value;
        onChanged();
      } else {
        memberAccessBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public Builder setMemberAccess(
        MemberAccessCommon.Builder builderForValue) {
      if (memberAccessBuilder_ == null) {
        memberAccess_ = builderForValue.build();
        onChanged();
      } else {
        memberAccessBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public Builder mergeMemberAccess(MemberAccessCommon value) {
      if (memberAccessBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            memberAccess_ != MemberAccessCommon.getDefaultInstance()) {
          memberAccess_ =
            MemberAccessCommon.newBuilder(memberAccess_).mergeFrom(value).buildPartial();
        } else {
          memberAccess_ = value;
        }
        onChanged();
      } else {
        memberAccessBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public Builder clearMemberAccess() {
      if (memberAccessBuilder_ == null) {
        memberAccess_ = MemberAccessCommon.getDefaultInstance();
        onChanged();
      } else {
        memberAccessBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public MemberAccessCommon.Builder getMemberAccessBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMemberAccessFieldBuilder().getBuilder();
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    public MemberAccessCommonOrBuilder getMemberAccessOrBuilder() {
      if (memberAccessBuilder_ != null) {
        return memberAccessBuilder_.getMessageOrBuilder();
      } else {
        return memberAccess_;
      }
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.MemberAccessCommon member_access = 2;</code>
     */
    private org.jetbrains.kotlin.protobuf.SingleFieldBuilder<
        MemberAccessCommon, MemberAccessCommon.Builder, MemberAccessCommonOrBuilder>
        getMemberAccessFieldBuilder() {
      if (memberAccessBuilder_ == null) {
        memberAccessBuilder_ = new org.jetbrains.kotlin.protobuf.SingleFieldBuilder<
            MemberAccessCommon, MemberAccessCommon.Builder, MemberAccessCommonOrBuilder>(
                getMemberAccess(),
                getParentForChildren(),
                isClean());
        memberAccess_ = null;
      }
      return memberAccessBuilder_;
    }

    private long super_ ;
    /**
     * <code>optional int64 super = 3;</code>
     */
    public boolean hasSuper() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 super = 3;</code>
     */
    public long getSuper() {
      return super_;
    }
    /**
     * <code>optional int64 super = 3;</code>
     */
    public Builder setSuper(long value) {
      bitField0_ |= 0x00000004;
      super_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 super = 3;</code>
     */
    public Builder clearSuper() {
      bitField0_ = (bitField0_ & ~0x00000004);
      super_ = 0L;
      onChanged();
      return this;
    }

    private int originName_ ;
    /**
     * <code>optional int32 origin_name = 4;</code>
     */
    public boolean hasOriginName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 origin_name = 4;</code>
     */
    public int getOriginName() {
      return originName_;
    }
    /**
     * <code>optional int32 origin_name = 4;</code>
     */
    public Builder setOriginName(int value) {
      bitField0_ |= 0x00000008;
      originName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 origin_name = 4;</code>
     */
    public Builder clearOriginName() {
      bitField0_ = (bitField0_ & ~0x00000008);
      originName_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrCall)
  }

  static {
    defaultInstance = new IrCall(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrCall)
}
