// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrFunctionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction)
    org.jetbrains.kotlin.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunctionBase base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunctionBase base = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrFunctionBase getBase();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunctionBase base = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrFunctionBaseOrBuilder getBaseOrBuilder();

  /**
   * <code>repeated int64 overridden = 2 [packed = true];</code>
   *
   * <pre>
   * TODO: supposed to be deleted
   * </pre>
   */
  java.util.List<java.lang.Long> getOverriddenList();
  /**
   * <code>repeated int64 overridden = 2 [packed = true];</code>
   *
   * <pre>
   * TODO: supposed to be deleted
   * </pre>
   */
  int getOverriddenCount();
  /**
   * <code>repeated int64 overridden = 2 [packed = true];</code>
   *
   * <pre>
   * TODO: supposed to be deleted
   * </pre>
   */
  long getOverridden(int index);
}