// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrGetEnumValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrGetEnumValue)
    org.jetbrains.kotlin.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 symbol = 1;</code>
   */
  boolean hasSymbol();
  /**
   * <code>required int64 symbol = 1;</code>
   */
  long getSymbol();
}