// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrGetClassOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrGetClass)
    org.jetbrains.kotlin.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression argument = 1;</code>
   */
  boolean hasArgument();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression argument = 1;</code>
   */
  IrExpression getArgument();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression argument = 1;</code>
   */
  IrExpressionOrBuilder getArgumentOrBuilder();
}