// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrTypeParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrTypeParameter)
    org.jetbrains.kotlin.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  IrDeclarationBase getBase();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  IrDeclarationBaseOrBuilder getBaseOrBuilder();

  /**
   * <code>required int32 name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required int32 name = 2;</code>
   */
  int getName();

  /**
   * <code>repeated int32 super_type = 3 [packed = true];</code>
   */
  java.util.List<Integer> getSuperTypeList();
  /**
   * <code>repeated int32 super_type = 3 [packed = true];</code>
   */
  int getSuperTypeCount();
  /**
   * <code>repeated int32 super_type = 3 [packed = true];</code>
   */
  int getSuperType(int index);
}