// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg}
 */
public final class IrVararg extends
    org.jetbrains.kotlin.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg)
    IrVarargOrBuilder {
  // Use IrVararg.newBuilder() to construct.
  private IrVararg(org.jetbrains.kotlin.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private IrVararg(boolean noInit) { this.unknownFields = org.jetbrains.kotlin.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final IrVararg defaultInstance;
  public static IrVararg getDefaultInstance() {
    return defaultInstance;
  }

  public IrVararg getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final org.jetbrains.kotlin.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final org.jetbrains.kotlin.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private IrVararg(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    org.jetbrains.kotlin.protobuf.UnknownFieldSet.Builder unknownFields =
        org.jetbrains.kotlin.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            elementType_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              element_ = new java.util.ArrayList<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement>();
              mutable_bitField0_ |= 0x00000002;
            }
            element_.add(input.readMessage(org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        element_ = java.util.Collections.unmodifiableList(element_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrVararg_descriptor;
  }

  protected org.jetbrains.kotlin.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrVararg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.class, org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.Builder.class);
  }

  public static org.jetbrains.kotlin.protobuf.Parser<IrVararg> PARSER =
      new org.jetbrains.kotlin.protobuf.AbstractParser<IrVararg>() {
    public IrVararg parsePartialFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
      return new IrVararg(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public org.jetbrains.kotlin.protobuf.Parser<IrVararg> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int ELEMENT_TYPE_FIELD_NUMBER = 1;
  private int elementType_;
  /**
   * <code>required int32 element_type = 1;</code>
   */
  public boolean hasElementType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 element_type = 1;</code>
   */
  public int getElementType() {
    return elementType_;
  }

  public static final int ELEMENT_FIELD_NUMBER = 2;
  private java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement> element_;
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  public java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement> getElementList() {
    return element_;
  }
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  public java.util.List<? extends org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder> 
      getElementOrBuilderList() {
    return element_;
  }
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  public int getElementCount() {
    return element_.size();
  }
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement getElement(int index) {
    return element_.get(index);
  }
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
   */
  public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder getElementOrBuilder(
      int index) {
    return element_.get(index);
  }

  private void initFields() {
    elementType_ = 0;
    element_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasElementType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getElementCount(); i++) {
      if (!getElement(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.jetbrains.kotlin.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, elementType_);
    }
    for (int i = 0; i < element_.size(); i++) {
      output.writeMessage(2, element_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt32Size(1, elementType_);
    }
    for (int i = 0; i < element_.size(); i++) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeMessageSize(2, element_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(byte[] data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(
      byte[] data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseDelimitedFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.jetbrains.kotlin.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg}
   */
  public static final class Builder extends
      org.jetbrains.kotlin.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg)
      org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargOrBuilder {
    public static final org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrVararg_descriptor;
    }

    protected org.jetbrains.kotlin.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrVararg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.class, org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.Builder.class);
    }

    // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.jetbrains.kotlin.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.jetbrains.kotlin.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getElementFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      elementType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (elementBuilder_ == null) {
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        elementBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrVararg_descriptor;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg getDefaultInstanceForType() {
      return org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.getDefaultInstance();
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg build() {
      org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg buildPartial() {
      org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg result = new org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.elementType_ = elementType_;
      if (elementBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = java.util.Collections.unmodifiableList(element_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.element_ = element_;
      } else {
        result.element_ = elementBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(org.jetbrains.kotlin.protobuf.Message other) {
      if (other instanceof org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg) {
        return mergeFrom((org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg other) {
      if (other == org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg.getDefaultInstance()) return this;
      if (other.hasElementType()) {
        setElementType(other.getElementType());
      }
      if (elementBuilder_ == null) {
        if (!other.element_.isEmpty()) {
          if (element_.isEmpty()) {
            element_ = other.element_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureElementIsMutable();
            element_.addAll(other.element_);
          }
          onChanged();
        }
      } else {
        if (!other.element_.isEmpty()) {
          if (elementBuilder_.isEmpty()) {
            elementBuilder_.dispose();
            elementBuilder_ = null;
            element_ = other.element_;
            bitField0_ = (bitField0_ & ~0x00000002);
            elementBuilder_ = 
              org.jetbrains.kotlin.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getElementFieldBuilder() : null;
          } else {
            elementBuilder_.addAllMessages(other.element_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasElementType()) {
        
        return false;
      }
      for (int i = 0; i < getElementCount(); i++) {
        if (!getElement(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int elementType_ ;
    /**
     * <code>required int32 element_type = 1;</code>
     */
    public boolean hasElementType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 element_type = 1;</code>
     */
    public int getElementType() {
      return elementType_;
    }
    /**
     * <code>required int32 element_type = 1;</code>
     */
    public Builder setElementType(int value) {
      bitField0_ |= 0x00000001;
      elementType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 element_type = 1;</code>
     */
    public Builder clearElementType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      elementType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement> element_ =
      java.util.Collections.emptyList();
    private void ensureElementIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        element_ = new java.util.ArrayList<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement>(element_);
        bitField0_ |= 0x00000002;
       }
    }

    private org.jetbrains.kotlin.protobuf.RepeatedFieldBuilder<
        org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder> elementBuilder_;

    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement> getElementList() {
      if (elementBuilder_ == null) {
        return java.util.Collections.unmodifiableList(element_);
      } else {
        return elementBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public int getElementCount() {
      if (elementBuilder_ == null) {
        return element_.size();
      } else {
        return elementBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement getElement(int index) {
      if (elementBuilder_ == null) {
        return element_.get(index);
      } else {
        return elementBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder setElement(
        int index, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement value) {
      if (elementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementIsMutable();
        element_.set(index, value);
        onChanged();
      } else {
        elementBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder setElement(
        int index, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder builderForValue) {
      if (elementBuilder_ == null) {
        ensureElementIsMutable();
        element_.set(index, builderForValue.build());
        onChanged();
      } else {
        elementBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder addElement(org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement value) {
      if (elementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementIsMutable();
        element_.add(value);
        onChanged();
      } else {
        elementBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder addElement(
        int index, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement value) {
      if (elementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElementIsMutable();
        element_.add(index, value);
        onChanged();
      } else {
        elementBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder addElement(
        org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder builderForValue) {
      if (elementBuilder_ == null) {
        ensureElementIsMutable();
        element_.add(builderForValue.build());
        onChanged();
      } else {
        elementBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder addElement(
        int index, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder builderForValue) {
      if (elementBuilder_ == null) {
        ensureElementIsMutable();
        element_.add(index, builderForValue.build());
        onChanged();
      } else {
        elementBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder addAllElement(
        java.lang.Iterable<? extends org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement> values) {
      if (elementBuilder_ == null) {
        ensureElementIsMutable();
        org.jetbrains.kotlin.protobuf.AbstractMessageLite.Builder.addAll(
            values, element_);
        onChanged();
      } else {
        elementBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder clearElement() {
      if (elementBuilder_ == null) {
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        elementBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public Builder removeElement(int index) {
      if (elementBuilder_ == null) {
        ensureElementIsMutable();
        element_.remove(index);
        onChanged();
      } else {
        elementBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder getElementBuilder(
        int index) {
      return getElementFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder getElementOrBuilder(
        int index) {
      if (elementBuilder_ == null) {
        return element_.get(index);  } else {
        return elementBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public java.util.List<? extends org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder> 
         getElementOrBuilderList() {
      if (elementBuilder_ != null) {
        return elementBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(element_);
      }
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder addElementBuilder() {
      return getElementFieldBuilder().addBuilder(
          org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.getDefaultInstance());
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder addElementBuilder(
        int index) {
      return getElementFieldBuilder().addBuilder(
          index, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.getDefaultInstance());
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement element = 2;</code>
     */
    public java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder> 
         getElementBuilderList() {
      return getElementFieldBuilder().getBuilderList();
    }
    private org.jetbrains.kotlin.protobuf.RepeatedFieldBuilder<
        org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder> 
        getElementFieldBuilder() {
      if (elementBuilder_ == null) {
        elementBuilder_ = new org.jetbrains.kotlin.protobuf.RepeatedFieldBuilder<
            org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElement.Builder, org.jetbrains.kotlin.backend.common.serialization.proto.IrVarargElementOrBuilder>(
                element_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        element_ = null;
      }
      return elementBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg)
  }

  static {
    defaultInstance = new IrVararg(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrVararg)
}
