// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.debug.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile}
 */
public final class IrWhile extends
    org.jetbrains.kotlin.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile)
    IrWhileOrBuilder {
  // Use IrWhile.newBuilder() to construct.
  private IrWhile(org.jetbrains.kotlin.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private IrWhile(boolean noInit) { this.unknownFields = org.jetbrains.kotlin.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final IrWhile defaultInstance;
  public static IrWhile getDefaultInstance() {
    return defaultInstance;
  }

  public IrWhile getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final org.jetbrains.kotlin.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final org.jetbrains.kotlin.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private IrWhile(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    org.jetbrains.kotlin.protobuf.UnknownFieldSet.Builder unknownFields =
        org.jetbrains.kotlin.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.jetbrains.kotlin.backend.common.serialization.proto.Loop.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = loop_.toBuilder();
            }
            loop_ = input.readMessage(org.jetbrains.kotlin.backend.common.serialization.proto.Loop.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(loop_);
              loop_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrWhile_descriptor;
  }

  protected org.jetbrains.kotlin.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrWhile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.class, org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.Builder.class);
  }

  public static org.jetbrains.kotlin.protobuf.Parser<IrWhile> PARSER =
      new org.jetbrains.kotlin.protobuf.AbstractParser<IrWhile>() {
    public IrWhile parsePartialFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
      return new IrWhile(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public org.jetbrains.kotlin.protobuf.Parser<IrWhile> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int LOOP_FIELD_NUMBER = 1;
  private org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop_;
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
   */
  public boolean hasLoop() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
   */
  public org.jetbrains.kotlin.backend.common.serialization.proto.Loop getLoop() {
    return loop_;
  }
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
   */
  public org.jetbrains.kotlin.backend.common.serialization.proto.LoopOrBuilder getLoopOrBuilder() {
    return loop_;
  }

  private void initFields() {
    loop_ = org.jetbrains.kotlin.backend.common.serialization.proto.Loop.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasLoop()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getLoop().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.jetbrains.kotlin.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, loop_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeMessageSize(1, loop_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(byte[] data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(
      byte[] data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseDelimitedFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      org.jetbrains.kotlin.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile}
   */
  public static final class Builder extends
      org.jetbrains.kotlin.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile)
      org.jetbrains.kotlin.backend.common.serialization.proto.IrWhileOrBuilder {
    public static final org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrWhile_descriptor;
    }

    protected org.jetbrains.kotlin.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrWhile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.class, org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.Builder.class);
    }

    // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        org.jetbrains.kotlin.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (org.jetbrains.kotlin.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getLoopFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (loopBuilder_ == null) {
        loop_ = org.jetbrains.kotlin.backend.common.serialization.proto.Loop.getDefaultInstance();
      } else {
        loopBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public org.jetbrains.kotlin.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return KotlinIr.internal_static_org_jetbrains_kotlin_backend_common_serialization_proto_IrWhile_descriptor;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile getDefaultInstanceForType() {
      return org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.getDefaultInstance();
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile build() {
      org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile buildPartial() {
      org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile result = new org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (loopBuilder_ == null) {
        result.loop_ = loop_;
      } else {
        result.loop_ = loopBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(org.jetbrains.kotlin.protobuf.Message other) {
      if (other instanceof org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile) {
        return mergeFrom((org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile other) {
      if (other == org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile.getDefaultInstance()) return this;
      if (other.hasLoop()) {
        mergeLoop(other.getLoop());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasLoop()) {
        
        return false;
      }
      if (!getLoop().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop_ = org.jetbrains.kotlin.backend.common.serialization.proto.Loop.getDefaultInstance();
    private org.jetbrains.kotlin.protobuf.SingleFieldBuilder<
        org.jetbrains.kotlin.backend.common.serialization.proto.Loop, org.jetbrains.kotlin.backend.common.serialization.proto.Loop.Builder, org.jetbrains.kotlin.backend.common.serialization.proto.LoopOrBuilder> loopBuilder_;
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public boolean hasLoop() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.Loop getLoop() {
      if (loopBuilder_ == null) {
        return loop_;
      } else {
        return loopBuilder_.getMessage();
      }
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public Builder setLoop(org.jetbrains.kotlin.backend.common.serialization.proto.Loop value) {
      if (loopBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loop_ = value;
        onChanged();
      } else {
        loopBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public Builder setLoop(
        org.jetbrains.kotlin.backend.common.serialization.proto.Loop.Builder builderForValue) {
      if (loopBuilder_ == null) {
        loop_ = builderForValue.build();
        onChanged();
      } else {
        loopBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public Builder mergeLoop(org.jetbrains.kotlin.backend.common.serialization.proto.Loop value) {
      if (loopBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            loop_ != org.jetbrains.kotlin.backend.common.serialization.proto.Loop.getDefaultInstance()) {
          loop_ =
            org.jetbrains.kotlin.backend.common.serialization.proto.Loop.newBuilder(loop_).mergeFrom(value).buildPartial();
        } else {
          loop_ = value;
        }
        onChanged();
      } else {
        loopBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public Builder clearLoop() {
      if (loopBuilder_ == null) {
        loop_ = org.jetbrains.kotlin.backend.common.serialization.proto.Loop.getDefaultInstance();
        onChanged();
      } else {
        loopBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.Loop.Builder getLoopBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLoopFieldBuilder().getBuilder();
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.LoopOrBuilder getLoopOrBuilder() {
      if (loopBuilder_ != null) {
        return loopBuilder_.getMessageOrBuilder();
      } else {
        return loop_;
      }
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Loop loop = 1;</code>
     */
    private org.jetbrains.kotlin.protobuf.SingleFieldBuilder<
        org.jetbrains.kotlin.backend.common.serialization.proto.Loop, org.jetbrains.kotlin.backend.common.serialization.proto.Loop.Builder, org.jetbrains.kotlin.backend.common.serialization.proto.LoopOrBuilder> 
        getLoopFieldBuilder() {
      if (loopBuilder_ == null) {
        loopBuilder_ = new org.jetbrains.kotlin.protobuf.SingleFieldBuilder<
            org.jetbrains.kotlin.backend.common.serialization.proto.Loop, org.jetbrains.kotlin.backend.common.serialization.proto.Loop.Builder, org.jetbrains.kotlin.backend.common.serialization.proto.LoopOrBuilder>(
                getLoop(),
                getParentForChildren(),
                isClean());
        loop_ = null;
      }
      return loopBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile)
  }

  static {
    defaultInstance = new IrWhile(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrWhile)
}
